title: Frostq 
description: Blog sobre desarrollo web y software. Tutoriales de programación | Coding beers

author:
  name: Diego López
  twitter: Frostq_
  github: Frostqui
  bio: Estudiando Software en la URJC. En esta página encontarás todo tipo de articulos y tutoriales sobre el desarrollo web y el mundo de la programación en general.


languages: ["es", "en"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

baseurl: 
exclude: ['README.md']
permalink: :title

plugins:
  - jekyll-redirect-from
  - jekyll-feed
